import 'package:flutter/material.dart';

class InfoTab2 extends StatelessWidget {
  const InfoTab2({super.key});

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: true,
      onPopInvokedWithResult: (didPop, result) {
        if (!didPop && Navigator.of(context).canPop()) {
          Navigator.of(context).pop();
        }
      },
      child: Scaffold(
        appBar: AppBar(
          leading: Container(
            padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
            child: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back,
                  size: 35,
                  weight: 700,
                  color: Colors.black,
                )),
          ),
        ),
        body: SingleChildScrollView(
          child: Container(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  margin: EdgeInsets.fromLTRB(16, 5, 0, 16),
                  child: Text('자동차는 정비가 생명입니다. \n 놓치기 쉬운 기본 관리법',style: TextStyle(fontSize: 20,fontWeight: FontWeight.w700, color: Color(0xff2A7FFF)),),
                ),
                Container(
                  margin: EdgeInsets.fromLTRB(10, 0, 20, 0),
                  width: double.infinity,
                  child: Center(
                    child: Column(
                      children: [
                        Image.asset('assets/images/info2-1.jpg', width: 350, height: 274),
                        Text('자동차를 처음 구매한 운전자들이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('가장 자주 놓치는 것 중 하나는 ',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('바로 ',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('"유지보수"',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('입니다.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 10,),
                        Text('차를 구매한 이후에도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('지속적인 관심과 관리는 필수인데요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('자동차는 단순한 기계가 아니라',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('정기적인 점검과 교체가 필요한',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('"소모품 덩어리"',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('라고',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('보시면 됩니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-2.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('우선 ',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('엔진오일 교체',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('는',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('가장 기본적인 유지보수 항목입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('엔진오일은 마치 사람의 혈액처럼',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('엔진 내부를 원활하게 작동시켜주는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('역할을 해요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('교체주기는 보통',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('5,000 ~ 7,000Km 또는 6개월을',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('기준으로 합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('이 주기를 넘기면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('엔진 성능 저하, 연비감소, 탄소 찌꺼기 누적 등',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('다양한 문제가 생길 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('특히 도심 주행 위주의 운전자는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('엔진이 자주 멈췄다 가는 환경에 놓이기 때문에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('더 자주 교체해줘야 할 수도 있습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-3.png', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('타이어 관리도',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('매우 중요합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('타이어 공기압은',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('주행 안정성, 연비, 제동력에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('큰 영향을 주기 떄문에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('한 달에 한 번은 꼭 점검해야 합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-4.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('공기압이 너무 낮으면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('타이어 수명이 줄고 연료 소묘량이 늘어나고요,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('너무 높으면 주행 중 미끄러지기 쉬워집니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-5.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('또한 타이어 마모 상태도 확인하세요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('일반적으로 타이어에는 ',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('마모 한계선을 표시해두는데,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('이 선보다 접지면이 닳았가면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('바로 교체해주는 게 안전합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-6.jpg', width: 350, height: 274),
                        Text('비 오는 날 타이어 성능이 저하되면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('제동거리가 평소보다 두배 이상',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('늘어날 수도 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-7.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Row(
                          children: [
                            Text('브레이크 패드',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('는 안전과 직결된 부품입니다.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 10,),
                        Text('평소에는 잘 모르다가,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('어느 순간 갑자기 소음이 나거나',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('제동거리가 길어졌을 때 이상을 느끼게 되죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('일반적으로는 2만 ~ 3만 km마다',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('교체가 필요하지만,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('급브레이크를 자주 사용하거나',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('산악 지역 운전이 많은 경우에는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('더 빠르게 닳기도 합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('브레이크가 밀리는 느낌이 들거나,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('페달을 밟을 때 진동이 느껴진다면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('점검을 받으세요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info2-8.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('또한',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('배터리, 에어컨 필터,',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('와이퍼 블레이드, 냉각수(부동액)도',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('계절에 따라 상태를 확인해야 하는데요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('배터리는 보통 2 ~ 3년 주기로',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('교체가 필요하며,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('특히 겨울철에 시동이 잘 안 걸릴 때는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('배터리 성능 저하를 의심해봐야 합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('와이퍼는 빗물이 깨끗하게 닦이지 않거나',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('소음이 나면 바로 교체하고,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('에어컨 필터는 미세먼지가 많은',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('봄철이 지나면 점검하는 것이 좋습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('요즘은 차량관리 앱이나',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('스마트 정비 서비스가 많아졌기 때문에,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('직접 관리가 어렵다면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('앱의 알림 기능을 활용해',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('주기적으로 점검 일정을 확인해 보세요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('작은 정비 하나하나가 모여',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('안전하고 효율적인 운전을 만들어줍니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('차량 정비는 단순한 유지가 아니라,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('사고를 예방하고 수명을 늘리는',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('투자입니다.',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 70,)
                      ],
                    ),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
