import 'package:flutter/material.dart';

class InfoTab3 extends StatelessWidget {
  const InfoTab3({super.key});

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: true,
      onPopInvokedWithResult: (didPop, result) {
        if (!didPop && Navigator.of(context).canPop()) {
          Navigator.of(context).pop();
        }
      },
      child: Scaffold(
        appBar: AppBar(
          leading: Container(
            padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
            child: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back,
                  size: 35,
                  weight: 700,
                  color: Colors.black,
                )),
          ),
        ),
        body: SingleChildScrollView(
          child: Container(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  margin: EdgeInsets.fromLTRB(16, 5, 0, 16),
                  child: Text('세차는 차량의 피부관리입니다. \n 제대로 알고 하세요.',style: TextStyle(fontSize: 20,fontWeight: FontWeight.w700, color: Color(0xff2A7FFF)),),
                ),
                Container(
                  margin: EdgeInsets.fromLTRB(10, 0, 20, 0),
                  width: double.infinity,
                  child: Center(
                    child: Column(
                      children: [
                        Image.asset('assets/images/info3-1.jpg', width: 350, height: 274),
                        Text('자동차 외관 관리에서',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('가장 기본이 되는 것이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('바로 세차입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('많은 운전자들이 세차를 단순히',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('"차를 예쁘게 보이게 하는"',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('미용 행위로 생각하지만,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('사실 세차는 자동차의',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('외관 보호, 도장면 유지,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('장기적인 차량 가치 유지와도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('직결되는 ',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('기초관리 루틴',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                decoration: TextDecoration.underline,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('입니다.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 10,),
                        Image.asset('assets/images/info3-2.png', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('세차의 적정 주기는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('일반적으로 2주에 한 번 정도가',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('적당하다고 알려져 있습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('하지만 실제로는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('날씨와 도로 환경에 따라 달라져요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('예를 들어',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('봄철 황사나 미세먼지, 여름철 장마',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('겨울철 제설제 등은',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('차체에 부식과 오염을 유발할 수 있기 때문에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('평소보다 더 자주 세차를 해야 합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('빗물 속에는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('황산, 질산 등의 산성 물질이 섞여 있어',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('도장면을 부식시킬 수 있기 때문입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Image.asset('assets/images/info3-3.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('외부 세차를 할 때는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('중성세제와 극세사 타월을',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('사용하는 것이 좋습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('강한 세정제나 거친 솔을 사용할 경우,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('차체에 미세한 흠집이 생겨',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('오히려 더 많은 오염을 유발하게 되죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('특히 여름철에는 햇빛 아래에서 세차를 하면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('물 얼룩이 생기기 쉬우니, 되도록이면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('그늘에서 진행하거나 해가 지는 시간대를',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('선택하는 것이 좋습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info3-4.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('내부 세차도 중요합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('차량 내부는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('미세먼지, 음식물, 사람의 체취 등이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('쌓이기 쉬운 공간입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('한 달에 한 번 정도는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('진공청소기로 바닥 매트, 시트 사이,',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('트렁크 등을 청소해주는 것이',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('위생상 좋습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info3-5.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('스티어링 휠, 기어봉, 문 손잡이 등',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('손이 자주 닿는 부분은',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('알코올 티슈로 닦아내면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('세균 제거에 효과적입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('여름철에는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('에어컨 필터 점검과 탈취제 사용도',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('추천드려요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info3-6.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('또 하나 놓치기 쉬운 부분이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('유리창 관리입니다.',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('실내 유리에 먼지나 지문이 묻어 있으면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('야간 운전 시 난반사 생기고',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('시야 확보에 어려움을 겪을 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('특히 겨울철에는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('김서림 방지제',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('를 뿌려두면',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('사고를 예방하는데 도움이 됩니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('세차를 정기적으로 하면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('차량의 외관뿐만 아니라',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('내부 위생과 도장면, 하부 부식 예방에도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('큰 도움이 됩니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('또한 차량을 중고로 되팔 때도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('높은 평가를 받을 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('작은 정성과 시간 투자로',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('차량의 수명을 늘릴 수 있다는 점,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('기억해두면 좋겠죠?',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 70,)
                      ],
                    ),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
