import 'package:flutter/material.dart';

class InfoTab4 extends StatelessWidget {
  const InfoTab4({super.key});

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: true,
      onPopInvokedWithResult: (didPop, result) {
        if (!didPop && Navigator.of(context).canPop()) {
          Navigator.of(context).pop();
        }
      },
      child: Scaffold(
        appBar: AppBar(
          leading: Container(
            padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
            child: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back,
                  size: 35,
                  weight: 700,
                  color: Colors.black,
                )),
          ),
        ),
        body: SingleChildScrollView(
          child: Container(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  margin: EdgeInsets.fromLTRB(16, 5, 0, 16),
                  child: Text('자동차는 말 대신 불빛으로 말합니다. \n 경고등은 SOS 신호예요.',style: TextStyle(fontSize: 20,fontWeight: FontWeight.w700, color: Color(0xff2A7FFF)),),
                ),
                Container(
                  margin: EdgeInsets.fromLTRB(10, 0, 20, 0),
                  width: double.infinity,
                  child: Center(
                    child: Column(
                      children: [
                        Image.asset('assets/images/info4-1.jpg', width: 350, height: 274),
                        Text('운전을 하다 보면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('어느 날 갑자기 대시보드에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('경고등이 켜지는 순간이 찾아옵니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('익숙한 운전자라도 살짝 긴장하게 되고,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('초보 운전자라면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('"이게 뭔가 고장난 건가?"',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('싶은 생각에 당황하기 마련이죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('그런데 그 순간이 사실은 자동차가',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('우리에게 보내는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('긴급 메시지',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('라는 사실,',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('알고 계셨나요?',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Image.asset('assets/images/info4-2.jpg', width: 350, height: 274),
                        Text('자동차의 경고등은 크게',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('색상과 모양',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('으로 나눌 수 있어요.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 10,),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('• 초록색/파랑색',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text(': 단순 알림 또는 활성화 상태',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('(예: 전조등 작동 중, 크루즈 컨트롤 작동 등)',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 5,),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('• 노란색/주황색',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text(': 주의 필요.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('차량에 이상 징후가 감지된 상태.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('가능한 빨리 점검 필요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 5,),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('• 빨간색',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text(': 즉시 조치가 필요한 상태.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('운행 중단 후 정비소 방문 필수',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info4-3.jpg', width: 350, height: 274),
                        Text('예를 들어,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('가장 자주 보이는 경고등 중 하나가',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('엔진 경고등',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('입니다.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 10,),
                        Text('노란색으로 표시되며, 엔진 센서가',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('비정상적인 연료 연소나',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('공기 흐름 문제 등을',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('감지한 경우에 뜨게 되죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('즉각 멈출 필요는 없지만,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('무시하고 계속 운전하다 보면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('엔진 손상으로 수백만원의',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('수리비가 발생할 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info4-4.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('브레이크 경고등은 ',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('빨간색으로 점등되며,',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('브레이크 오일 부족이나 제동 시스템에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('문제가 생긴 경우 나타납니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('이 경우 절대 주행을 이어가면 안됩니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('즉시 차량을 정차하고 정비소에 문의해야합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('브레이크는 차량의 가장 중요한',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('안전장치이기 때문에',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('문제를 방치하면 사고로 직결될 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Image.asset('assets/images/info4-5.jpg', width: 350, height: 274),
                        Text('타이어 공기압 경고등도',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('많은 운전자들이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('자주 접하게 되는 경고등입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('특히 기온 변화가 심한 계절에는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('공기압 변화가 커서',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('자주 뜨게 되는데요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('타이어 공기압이 낮으면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('주행 안정성에 영향을 미치고,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('타이어 파손이나 연비 저하로',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('이어질 수 있습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('이 경고등이 켜지면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('바로 공기압을 체크하고',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('조정해주는 것이 좋습니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info4-6.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('최근 출시되는 차량들은',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('TPMS(타이어 공기압 자동 감지 시스템),',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('자동 브레이크 제어시스템,',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('하이브리드/전기차 배터리 경고등 등',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('다양한 고급 경고등 기능을 갖추고 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('운전자는 차량 설명서를 통해',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('자신의 차량에 어떤 경고등이 있는지,',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('각각이 어떤 의미를 가지는지',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('미리 익혀두는 것이 중요합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('요약하자면, 경고등은',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('"자동차가 스스로 문제를 알려주는 시스템"',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('이를 무시하면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('문제가 더 커지거나 사고로 이어질 수 있고,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('결국 수리비와 시간 낭비로 돌아오게 되죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('경고등이 켜졌을 땐 당황하지 말고,',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('차분히 원인을 확인하고',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('필요한 조치를 취하세요.',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('그것이 나와 타인의',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('안전을 지키는 ',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('첫걸음',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('입니다.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 70,)
                      ],
                    ),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
