import 'package:flutter/material.dart';

class InfoTab1 extends StatelessWidget {
  const InfoTab1({super.key});

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: true,
      onPopInvokedWithResult: (didPop, result) {
        if (!didPop && Navigator.of(context).canPop()) {
          Navigator.of(context).pop();
        }
      },
      child: Scaffold(
        appBar: AppBar(
          leading: Container(
            padding: EdgeInsets.fromLTRB(5, 0, 0, 0),
            child: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back,
                  size: 35,
                  weight: 700,
                  color: Colors.black,
                )),
          ),
        ),
        body: SingleChildScrollView(
          child: Container(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  margin: EdgeInsets.fromLTRB(16, 5, 0, 16),
                  child: Text('내 라이프스타일에 맞는 차, \n 어떻게 고를까?',style: TextStyle(fontSize: 20,fontWeight: FontWeight.w700, color: Color(0xff2A7FFF)),),
                ),
                Container(
                  margin: EdgeInsets.fromLTRB(10, 0, 20, 0),
                  width: double.infinity,
                  child: Center(
                    child: Column(
                      children: [
                        Image.asset('assets/images/info1-1.jpg', width: 350, height: 274),
                        Text('처음 자동차를 구매하려는 순간,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'gamjaflower',
                            // color: Colors.black,
                          ),
                        ),
                        Text('누구나 고민에 빠집니다.',
                          style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('"어떤 차가 나에게 잘 맞을까?"',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('"신차가 좋을까, 중고차가 좋을까?"',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('"연비는 얼마나 중요할까?"',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('같은 질문들이 머릿속을 맴돌죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        SizedBox(height: 20,),
                        Text('사실 자동차는 단순한 이동 수단이 아니라,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('매일의 삶과 연결된 ',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                                // color: Colors.black,
                              ),
                            ),
                            Text('"생활의 파트너"',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                                // color: Colors.black,
                              ),
                            ),
                            Text('입니다.',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                                // color: Colors.black,
                              ),
                            ),
                          ],
                        ),
                        SizedBox(height: 20,),
                        Text('그래서 자신의 라이프 스타일을',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('먼저 들여다보는 것이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('아주 중요해요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info1-2.jpg', width: 350, height: 274),
                        SizedBox(height: 10,),
                        Text('예를 들어,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('출퇴근 거리나 평소 주행 경로를',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('떠올려보세요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        SizedBox(height: 20,),
                        Text('하루 평균 주행거리가 길고',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('고속도로 비중이 높다면,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('연비 좋은 디젤이나 하이브리드 차량이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('유리할 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info1-3.jpg', width: 350, height: 274),
                        SizedBox(height: 20,),
                        Text('반대로 도심 위주의 단거리 주행이 많다면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        Text('작은 경차나 전기차도 좋은 선택입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            decoration: TextDecoration.underline,
                            fontFamily: 'nanum_pen',
                            // color: Colors.black,
                          ),
                        ),
                        SizedBox(height: 20,),
                        Image.asset('assets/images/info1-4.jpg', width: 350, height: 274),
                        SizedBox(height: 20,),
                        Text('주차 공간이 좁거나 이동이 잦다면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('자체가 작은 모델이 훨씬 편하고요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Image.asset('assets/images/info1-5.jpg', width: 160, height: 150,fit: BoxFit.contain,),
                            SizedBox(width: 20,),
                            Image.asset('assets/images/info1-6.jpg', width: 160, height: 150,fit: BoxFit.contain,),
                          ],
                        ),
                        SizedBox(height: 20,),
                        Text('또 한 가지,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('"몇 명이 타는가"도',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w600,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('중요한 포인트입니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('혼자 또는 둘이 타는 용도라면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('소형 해치백이나 준중형 세단도 충분하지만,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('가족 단위라면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('뒷자석 공간과 ',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('트렁크 용량',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('도',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('꼼꼼히 따져봐야 해요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Image.asset('assets/images/info1-7.jpg', width: 350, height: 274),
                        SizedBox(height: 20,),
                        Text('유모차나 캠핑 장비 등 짐이 많다면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('SUV나 왜건 타입이 실용적이겠죠.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Image.asset('assets/images/info1-8.jpg', width: 350, height: 274),
                        SizedBox(height: 20,),
                        Text('자동차는 구입 비용 외에도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('세금, 보혐료, 정비 비용, 주유비',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('같은',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('유지비가 꾸준히 들기 때문에,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('단순히 "할부로 월 얼마"만 보는 건 위험합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('처음엔 저렴하게 느껴져도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('1년, 3년 단위로 따져보면',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('총 소요 비용이 크게 달라질 수 있어요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('중고차를 고려한다면 더욱 신중해야 해요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('외관만 보고 결정하지 말고,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('사고이력, 소모품 교체 여부,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('주행거리, 정비기록까지',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('꼼꼼히 확인해야합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('전문업체나 신회할 수 있는',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('판매자를 통해 확인된 차량인지',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('꼭 점검하세요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 10,),
                        Text('마지막으로,',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('"이차가 지금의 내 삶을 더',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('편하게 만들어줄 수 있는가?"',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('라는 질문을 스스로에게 해보세요.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('브랜드 이미지, 옵션의 화려함, 유행보다도',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('나에게 맞는 차',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.w600,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                            Text('를',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.w500,
                                fontFamily: 'nanum_pen',
                              ),
                            ),
                          ],
                        ),
                        Text('고르는 것이',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        Text('무엇보다 중요합니다.',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w500,
                            fontFamily: 'nanum_pen',
                          ),
                        ),
                        SizedBox(height: 70,)
                      ],
                    ),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
