// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAco-3hJsvgH-hbdoydog4gdJvO61PhFeo',
    appId: '1:94069309394:web:050fc98fdfffc16bde920b',
    messagingSenderId: '94069309394',
    projectId: 'carcheck-6aa9e',
    authDomain: 'carcheck-6aa9e.firebaseapp.com',
    storageBucket: 'carcheck-6aa9e.firebasestorage.app',
    measurementId: 'G-YX8Q17Z856',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdXBqEyj3kTvWVs5PcGdY6EviBLQk6lY',
    appId: '1:94069309394:android:9686a0c14a107340de920b',
    messagingSenderId: '94069309394',
    projectId: 'carcheck-6aa9e',
    storageBucket: 'carcheck-6aa9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqOG1Cc9d2w-6ghPHp72gU73QX901l1wg',
    appId: '1:94069309394:ios:f00d840ee2a1ba13de920b',
    messagingSenderId: '94069309394',
    projectId: 'carcheck-6aa9e',
    storageBucket: 'carcheck-6aa9e.firebasestorage.app',
    androidClientId: '94069309394-nn5ubimeo7dqj1njsck2319ctlcaeeuj.apps.googleusercontent.com',
    iosClientId: '94069309394-e388e8n1lqs6a3i9knrptvn3dap57dqn.apps.googleusercontent.com',
    iosBundleId: 'com.purem.carChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqOG1Cc9d2w-6ghPHp72gU73QX901l1wg',
    appId: '1:94069309394:ios:f00d840ee2a1ba13de920b',
    messagingSenderId: '94069309394',
    projectId: 'carcheck-6aa9e',
    storageBucket: 'carcheck-6aa9e.firebasestorage.app',
    androidClientId: '94069309394-nn5ubimeo7dqj1njsck2319ctlcaeeuj.apps.googleusercontent.com',
    iosClientId: '94069309394-e388e8n1lqs6a3i9knrptvn3dap57dqn.apps.googleusercontent.com',
    iosBundleId: 'com.purem.carChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAco-3hJsvgH-hbdoydog4gdJvO61PhFeo',
    appId: '1:94069309394:web:26ac30d2569ee3b2de920b',
    messagingSenderId: '94069309394',
    projectId: 'carcheck-6aa9e',
    authDomain: 'carcheck-6aa9e.firebaseapp.com',
    storageBucket: 'carcheck-6aa9e.firebasestorage.app',
    measurementId: 'G-CNPNK47FLJ',
  );

}